name: Release
concurrency: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: onlyspans/gh-workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
    with:
      image_name: events
      helm_release: events-staging
      kube_namespace: events
      helm_dir: ./deployments/kubernetes/helm
      dockerfile: deployments/docker/Dockerfile
    secrets: inherit
