# Usage: docker compose -f compose.yaml -f compose.kafka.yaml up

services:
  zookeeper:
    profiles: [""]

  kafka:
    profiles: [""]

  events:
    environment:
      - KAFKA_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
